### ISSUE TITLE
/goestools/src/decoder/derandomizer.h:14:27: error: ‘size_t’ has not been declared

### ISSUE THREAD

**Issue by dive76** [sam210723/goestools#9]
Getting the following error during make:

[ 73%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/derandomizer.cc.o
In file included from /home/lars/goestools/src/decoder/derandomizer.cc:1:
/home/lars/goestools/src/decoder/derandomizer.h:14:27: error: ‘size_t’ has not been declared
   14 |   void run(uint8_t* data, size_t len);
      |                           ^~~~~~
/home/lars/goestools/src/decoder/derandomizer.cc:33:6: error: no declaration matches ‘void decoder::Derandomizer::run(uint8_t*, size_t)’
   33 | void Derandomizer::run(uint8_t* data, size_t len) {
      |      ^~~~~~~~~~~~
In file included from /home/lars/goestools/src/decoder/derandomizer.cc:1:
/home/lars/goestools/src/decoder/derandomizer.h:14:8: note: candidate is: ‘void decoder::Derandomizer::run(uint8_t*, int)’
   14 |   void run(uint8_t* data, size_t len);
      |        ^~~
/home/lars/goestools/src/decoder/derandomizer.h:10:7: note: ‘class decoder::Derandomizer’ defined here
   10 | class Derandomizer {
      |       ^~~~~~~~~~~~
make[2]: *** [src/decoder/CMakeFiles/packetizer.dir/build.make:95: src/decoder/CMakeFiles/packetizer.dir/derandomizer.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1681: src/decoder/CMakeFiles/packetizer.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by dive76** [comment]
I was using the 64-bit version of the OS. In 32 bit no errors.

**Comment by sam210723** [comment]
Yes I believe `size_t` is defined differently on 64-bit architectures which I have not done much testing with. Glad you've got it working.
